 - name: install the tomcat,maven
   become: yes 
   apt: name={{item}} update_cache=yes state=present
   with_items:
             - tomcat7
             - maven
               

 - name: Start the tomcat service 
   service: name=tomcat7 state=started

- name: copy the shellscripts
  copy: src=/home/boon/scripts/calc.sh dest=/home/ubuntu/
- name: copy the template file
  template: src=avg.j2 dest=/home/ubuntu/avg.sh
